const $=s=>document.querySelector(s);const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const team=n=>TEAMS.find(t=>t.name===n);const ALIASES={'Prajwal P.K':'Prajwal','P.K':'Prajwal','J. Root':'Joe Root','S. Gill':'Shubman Gill','Bethell':'Jacob Bethell','Cox':'Jordan Cox','Bhuvi':'Bhuvneshwar Kumar','Bumrah':'Jasprit Bumrah','Rashid':'Rashid Khan','Patidar':'Rajat Patidar','Salt':'Phil Salt','Root':'Joe Root','Smith':'Steve Smith','Rahane':'Ajinkya Rahane','MSD':'Mahendra Singh Dhoni','Umesh':'Umesh Yadav','M. Siraj':'Mohammed Siraj','S. Iyer':'Shreyas Iyer','Rabada':'Kagiso Rabada','Rickelton':'Ryan David Rickelton','Ben Mayes':'Ben Angus Mayes','Vaibhav':'Vaibhav Sooryavanshi'};const player=n=>PLAYERS.find(p=>p.name===(ALIASES[n]||n));
function matchCard(m){return `<article class="match" onclick="showMatch(${m.id})"><div class="matchhead"><span>Match ${m.id}</span><span>Season 11</span></div><div class="versus"><div><img src="${team(m.a).logo}"><b>${m.a}</b><strong>${m.scores[0]}</strong></div><span>VS</span><div><img src="${team(m.b).logo}"><b>${m.b}</b><strong>${m.scores[1]}</strong></div></div><p class="result">${m.result}</p><small>Venue: International Ground</small><button class="smallbtn">View Scorecard</button></article>`}
function renderMatches(){$('#matchGrid').innerHTML=MATCHES.map(matchCard).join('')}
function renderTeams(){$('#teamGrid').innerHTML=TEAMS.map(t=>`<article class="team" onclick="location.hash='players';document.querySelector('#filter').value='${t.name}';renderPlayers()"><img src="${t.logo}"><h3>${t.name}</h3><p>${t.ground}</p><small>${t.players.length} players</small></article>`).join('')}
function renderPlayers(){const q=$('#search').value.toLowerCase(),f=$('#filter').value;const list=PLAYERS.filter(p=>(f==='all'||p.team===f)&&p.name.toLowerCase().includes(q));$('#playerGrid').innerHTML=list.map(p=>`<article class="player" onclick="showPlayer('${esc(p.name)}')"><img src="${p.photo}" onerror="this.src='assets/player-placeholder.svg'"><div><h3>${p.name}</h3><p>${p.team}</p><span>${p.role}</span></div><b class="runs">${p.s11.runs} <small>runs</small></b></article>`).join('')||'<p>No players found.</p>'}
function initFilter(){$('#filter').innerHTML='<option value="all">All teams</option>'+TEAMS.map(t=>`<option>${t.name}</option>`).join('')}
function profileStats(p){const s=p.s11;const career=p.pre?{matches:p.pre.matches+s.matches,runs:p.pre.runs+s.runs,avg:((p.pre.runs+s.runs)/Math.max(1,p.pre.matches+s.matches)).toFixed(1),fifties:p.pre.fifties+s.fifties,hundreds:p.pre.hundreds+s.hundreds,highest:Math.max(p.pre.highest,s.highest)}:{matches:s.matches,runs:s.runs,avg:(s.runs/Math.max(1,s.matches)).toFixed(1),fifties:s.fifties,hundreds:s.hundreds,highest:s.highest};return {s,career}}
function showPlayer(name){const p=player(name);if(!p)return;const x=profileStats(p);$('#modalBody').innerHTML=`<div class="profiletop"><img src="${p.photo}" onerror="this.src='assets/player-placeholder.svg'"><div><span class="eyebrow">PLAYER PROFILE</span><h2>${p.name}</h2><p>${p.team} • ${p.role}</p><p>${p.bat} • ${p.bowl}</p><p>${p.place} • Jersey No. ${p.number}</p></div></div><h3>Season 11</h3><div class="prostats">${card('Runs',x.s.runs)}${card('Wickets',x.s.wickets)}${card('50s',x.s.fifties)}${card('100s',x.s.hundreds)}${card('Average',(x.s.runs/Math.max(1,x.s.matches)).toFixed(1))}${card('Highest Score',x.s.highest)}</div><h3>HPL Career</h3><div class="prostats">${card('Matches',x.career.matches)}${card('Runs',x.career.runs)}${card('Average',x.career.avg)}${card('50s',x.career.fifties)}${card('100s',x.career.hundreds)}${card('Highest Score',x.career.highest)}</div>`;$('#modal').classList.remove('hidden')}
function card(a,b){return `<div><small>${a}</small><strong>${b}</strong></div>`}
function showMatch(id){const m=MATCHES.find(x=>x.id===id);const score=(rows)=>rows.map(([n,r])=>`<tr onclick="showPlayer('${esc(n)}')"><td>${n}</td><td>${r}</td></tr>`).join('');const potm=player(m.potm);$('#modalBody').innerHTML=`<div class="matchmodal"><span class="eyebrow">MATCH ${m.id} • SEASON 11</span><h2>${m.a} vs ${m.b}</h2><div class="bigscore"><div><img src="${team(m.a).logo}"><b>${m.a}</b><strong>${m.scores[0]}</strong></div><div>VS</div><div><img src="${team(m.b).logo}"><b>${m.b}</b><strong>${m.scores[1]}</strong></div></div><p class="result">${m.result}</p><div class="scoretables"><div><h3>${m.a} Batting</h3><table><tbody>${score(m.batA)}</tbody></table></div><div><h3>${m.b} Batting</h3><table><tbody>${score(m.batB)}</tbody></table></div></div><div class="potm"><span>PLAYER OF THE MATCH</span><b>${m.potm}</b><small>Selected from the recorded performance; scorecard data can be updated later with wickets.</small></div></div>`;$('#modal').classList.remove('hidden')}
function renderStats(){const rows=LOCAL_PLAYERS.map(p=>({p,s:p.s11}));const mostRuns=[...rows].sort((a,b)=>b.s.runs-a.s.runs)[0],highest=[...rows].sort((a,b)=>b.s.highest-a.s.highest)[0],most50=[...rows].sort((a,b)=>b.s.fifties-a.s.fifties)[0],most100=[...rows].sort((a,b)=>b.s.hundreds-a.s.hundreds)[0];$('#statCards').innerHTML=[['Most Runs',mostRuns.p.name+' — '+mostRuns.s.runs],['Highest Score',highest.p.name+' — '+highest.s.highest],['Most 50s',most50.p.name+' — '+most50.s.fifties],['Most 100s',most100.p.name+' — '+most100.s.hundreds],['Best Average','Calculated from Season 11 runs/matches'],['Most Wickets','Wicket totals pending recorded wicket figures']].map(x=>`<div>${x[0]}<strong>${x[1]}</strong></div>`).join('')}
function renderRecords(){const career=LOCAL_PLAYERS.filter(p=>p.pre).map(p=>({p,s:p.pre}));const r=career.sort((a,b)=>b.s.runs-a.s.runs)[0],h=[...career].sort((a,b)=>b.s.highest-a.s.highest)[0];$('#recordCards').innerHTML=`<div>Most Runs<strong>${r.p.name} — ${r.s.runs+p.runs}</strong></div><div>Highest Individual Score<strong>${h.p.name} — ${Math.max(h.s.highest,h.p.s11.highest)}</strong></div><div>Most 100s<strong>Season 11 + previous records combined in player profiles</strong></div><div>Most 50s<strong>Season 11 + previous records combined in player profiles</strong></div>`}
$('#enter').onclick=()=>$('#intro').classList.add('hide');$('#skip').onclick=()=>$('#intro').classList.add('hide');setTimeout(()=>$('#intro').classList.add('hide'),6500);$('#menu').onclick=()=>document.querySelector('header').classList.toggle('open');$('#close').onclick=()=>$('#modal').classList.add('hidden');$('#modal').onclick=e=>{if(e.target.id==='modal')$('#modal').classList.add('hidden')};$('#search').oninput=renderPlayers;$('#filter').onchange=renderPlayers;renderMatches();renderTeams();initFilter();renderPlayers();renderStats();renderRecords();
