const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
function team(name){return HPL_TEAMS.find(t=>t.name===name)}
function renderMatches(){$('#matchesGrid').innerHTML=HPL_MATCHES.map((m,i)=>`<article class="card"><div class="match-top"><span>Match ${i+1}</span><span>Season 11</span></div><div class="teams"><div class="team-name">${m.a}</div><span class="vs">VS</span><div class="team-name">${m.b}</div></div><p><b>${m.score}</b></p><p class="result">${m.result}</p><small>Venue: ${team(m.a)?.ground||'International Ground'}</small></article>`).join('')}
function renderTeams(){$('#teamsGrid').innerHTML=HPL_TEAMS.map(t=>`<article class="team-card"><img class="team-logo" src="${t.logo}" alt="${t.name} logo"><h3>${t.name}</h3><p>Home: ${t.ground}</p><p>${t.players.length} players</p></article>`).join('')}
function fillFilter(){$('#teamFilter').innerHTML='<option value="all">All teams</option>'+HPL_TEAMS.map(t=>`<option>${t.name}</option>`).join('')}
function renderPlayers(){const q=$('#playerSearch').value.toLowerCase(),f=$('#teamFilter').value;const ps=HPL_PLAYERS.filter(p=>(f==='all'||p.team===f)&&p.name.toLowerCase().includes(q));$('#playersGrid').innerHTML=ps.map(p=>`<article class="player-card" data-name="${p.name}"><img class="player-avatar" src="${p.photo}" alt="${p.name}"><h3>${p.name}</h3><p>${p.team}</p><p>${p.role}</p></article>`).join('')||'<p>No players found.</p>';$$('.player-card').forEach(c=>c.onclick=()=>showPlayer(c.dataset.name))}
function showPlayer(name){const p=HPL_PLAYERS.find(x=>x.name===name);if(!p)return;$('#modalBody').innerHTML=`<div class="profile"><img src="${p.photo}" alt="${p.name}"><div><h2>${p.name}</h2><p>${p.team} • ${p.role}</p><p>${p.bat}<br>${p.bowl}<br>${p.place} • No. ${p.number}</p></div></div><div class="profile-stats"><div><b>HPL Runs</b><strong>${p.runs}</strong></div><div><b>HPL Wickets</b><strong>${p.wickets}</strong></div><div><b>Most 100s</b><strong>—</strong></div><div><b>Most 50s</b><strong>—</strong></div><div><b>Average</b><strong>—</strong></div><div><b>Best Bowling</b><strong>—</strong></div><div><b>Highest Individual Score</b><strong>—</strong></div><div><b>HPL Career</b><strong>Season 11</strong></div></div>`;$('#modal').classList.remove('hidden')}
const closeIntro=()=>{$('#welcome').classList.add('hide');location.hash='#home';}; $('#enterBtn').onclick=closeIntro; $('#skipBtn').onclick=closeIntro; setTimeout(()=>{if(!$('#welcome').classList.contains('hide')) closeIntro();},6500);$('#closeModal').onclick=()=>$('#modal').classList.add('hidden');$('#modal').onclick=e=>{if(e.target.id==='modal')$('#modal').classList.add('hidden')};$('#menuBtn').onclick=()=>$('.site-header').classList.toggle('nav-open');$('#playerSearch').oninput=renderPlayers;$('#teamFilter').onchange=renderPlayers;
renderMatches();renderTeams();fillFilter();renderPlayers();
